name: or4d-clean
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - numpy<2
  - scipy
  - h5py
  - pyyaml
  - matplotlib
  - scikit-image
  - pymatgen
  - pyxem=0.21
  - pip:
      - "py4DSTEM[acom]==0.14.18"
      - "cuda-python==12.9.7"
